schema-prisma-checkout-created
theodevoid/mikrommerce pull request #10
Opened 2023-05-13 10:33 UTC by chinmareno

schema prisma buat checkout bg

2023-05-13 10:35 UTC, theodevoid commented
Thank youu 🙌 . Tapi ini kok isi commit-nya nambahin submodule ya?

2023-05-13 11:03 UTC, theodevoid requested changes
Jangan dibikin jadi submodule yaa, mungkin  salah cara clone-nya

2023-05-13 12:04 UTC, chinmareno commented
lah iya ya

2023-05-13 12:35 UTC, theodevoid requested changes
Ini masuknya bikin file schema prisma baru. Update yang existing aja yaa.

2023-05-14 02:12 UTC, chinmareno commented
oke  bang

2023-06-07 16:36 UTC, closed without merging